---
shared: &1
- ".dockerignore"
- Dockerfile.updater-core
- common/**
- updater/Gemfil*
- omnibus/**
- ".github/workflows/ci.yml"
rakefile_tests:
- rakelib/**
- Rakefile
- script/test-rakefile
dry_run:
- *1
- bin/dry-run.rb
- bin/spec/**
bun:
- *1
- bun/**
bundler:
- *1
- bundler/**
cargo:
- *1
- cargo/**
common:
- *1
- "**/**"
composer:
- *1
- composer/**
conda:
- *1
- conda/**
devcontainers:
- *1
- devcontainers/**
docker:
- *1
- docker/**
docker_compose:
- *1
- docker_compose/**
dotnet_sdk:
- *1
- dotnet_sdk/**
elm:
- *1
- elm/**
git_submodules:
- *1
- git_submodules/**
github_actions:
- *1
- github_actions/**
go_modules:
- *1
- go_modules/**
gradle:
- *1
- maven/**
- gradle/**
helm:
- *1
- helm/**
hex:
- *1
- hex/**
maven:
- *1
- maven/**
npm_and_yarn:
- *1
- npm_and_yarn/**
nuget:
- *1
- nuget/**
pub:
- *1
- pub/**
python:
- *1
- python/**
rust_toolchain:
- *1
- rust_toolchain/**
swift:
- *1
- swift/**
terraform:
- *1
- terraform/**
test_ecosystem:
- *1
- test_ecosystem/**
uv:
- *1
- uv/**
vcpkg:
- *1
- vcpkg/**
