name: CI
on:
  push:
    branches:
      - "main"
  pull_request:
    paths-ignore:
      - 'CHANGELOG.md'
      - 'common/lib/dependabot/version.rb'
    branches:
      - "main"
jobs:
  ci:
    name: "${{ matrix.suite.name }}"
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 1
      EARTHLY_DISABLE_ANALYTICS: true
    strategy:
      fail-fast: false
      matrix:
        suite:
          - { path: bundler, name: "Bundler" }
          - { path: cargo, name: "Cargo" }
          - { path: common, name: "Common" }
          - { path: composer, name: "Composer" }
          - { path: docker, name: "Docker" }
          - { path: elm, name: "Elm" }
          - { path: git_submodules, name: "Git Submodules" }
          - { path: github_actions, name: "GitHub Actions" }
          - { path: go_modules, name: "Go Modules" }
          - { path: gradle, name: "Gradle" }
          - { path: hex, name: "Hex" }
          - { path: maven, name: "Maven" }
          - { path: npm_and_yarn, name: "npm and Yarn" }
          - { path: nuget, name: "NuGet" }
          - { path: python, name: "Python" }
          - { path: pub, name: "Pub" }
          - { path: terraform, name: "Terraform" }
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Earthly
        uses: earthly/actions-setup@v1
        with:
          version: "v0.6.10"
      - name: Run Tests
        run: |
          earthly --ci ./${{ matrix.suite.path }}+test
        env:
          DEPENDABOT_TEST_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SUITE_NAME: ${{ matrix.suite.name }}
          RAISE_ON_WARNINGS: true
      - name: Lint
        run: |
          earthly --ci ./${{ matrix.suite.path }}+lint
