name: CI
on:
  push:
    branches:
      - "main"
  pull_request:
    paths-ignore:
      - "CHANGELOG.md"
      - "common/lib/dependabot/version.rb"
    branches:
      - "main"
  schedule:
    - cron: "0 0 * * *"

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        suite:
          - bundler1
          - bundler2
          - cargo
          - common
          - composer
          - docker
          - elm
          - git_submodules
          - github_actions
          - go_modules
          - gradle
          - hex
          - maven
          - npm_and_yarn
          - nuget
          - omnibus
          - python
          - python_slow
          - pub
          - terraform
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build dependabot-core image
        run: |
          ./bin/ci-test build-core
      - name: Build dependabot-core-ci image
        run: |
          ./bin/ci-test build-core-ci
      - name: Run ${{ matrix.suite.name }} tests
        env:
          LOCAL_GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./bin/ci-test run-suite ${{ matrix.suite }}

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ./bin/lint
