name: Push Docker Images
env:
  CORE_IMAGE: "dependabot/dependabot-core"
  CORE_IMAGE_MIRROR: "ghcr.io/dependabot/dependabot-core"
on:
  push:
    branches:
      - main
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
jobs:
  push-core-image:
    name: Push dependabot-core image
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'dependabot/dependabot-core' }}
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Log in to the Docker registry
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Log in to GHCR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Setup Earthly
        uses: earthly/actions-setup@v1
        with:
          version: "v0.6.10"
      - name: Build and push dependabot-core image
        run: |
          earthly --ci --push --remote-cache=$CORE_IMAGE --max-remote-cache +docker --tag=latest
      - name: Push latest image
        run: |
          docker tag "$CORE_IMAGE:latest" "$CORE_IMAGE_MIRROR:latest"
          docker push "$CORE_IMAGE_MIRROR:latest"
      - name: Push image version tags
        if: "contains(github.ref, 'refs/tags')"
        run: |
          VERSION="$(grep -Eo "[0-9]+\.[0-9]+\.[0-9]+" common/lib/dependabot/version.rb)"
          docker tag "$CORE_IMAGE:latest" "$CORE_IMAGE:$VERSION"
          docker push "$CORE_IMAGE:$VERSION"
          docker tag "$CORE_IMAGE:latest" "$CORE_IMAGE_MIRROR:$VERSION"
          docker push "$CORE_IMAGE_MIRROR:$VERSION"
  push-development-image:
    name: Push dependabot-core-development image to GHCR
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    needs: push-core-image
    env:
      DEV_IMAGE: ghcr.io/dependabot/dependabot-core-development
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Log in to GHCR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build and push dependabot-core-development image
        run: |
          earthly --ci --push --remote-cache=$CORE_IMAGE --max-remote-cache +docker --tag=latest --development=true
      - name: Push image version tags
        if: "contains(github.ref, 'refs/tags')"
        run: |
          VERSION="$(grep -Eo "[0-9]+\.[0-9]+\.[0-9]+" common/lib/dependabot/version.rb)"
          docker tag "$DEV_IMAGE:latest" "$DEV_IMAGE:$VERSION"
          docker push "$DEV_IMAGE:$VERSION"
